name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'research/luminar-4b'
        required: true

jobs:
  push_to_replicate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Push
        run: cog push r8.im/${{ inputs.model_name }}
